name = "dong-rt"
main = "src/index.js"
compatibility_date = "2025-09-01"
workers_dev = true

[[durable_objects.bindings]]
name = "HUB"
class_name = "Hub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Hub"]
